Feature/navbar
GolemT/Flutter_FinanceTracker pull request #1
Opened 2024-05-17 12:05 UTC by Phange38

2024-05-28 09:06 UTC, GolemT commented
Navbar passt sich nicht screen size an
![image](https://github.com/GolemT/Flutter_FinanceTracker/assets/79120567/f1976e07-980b-49bb-98b4-8b46aca6fbc4)
hier nochmal schauen das man das ganze anpasst. Außerdem ist der 'Add' Button um einiges Größer als die Navbar

2024-05-28 09:14 UTC, GolemT requested changes
Bitte schauen das man erst die navbar responsive zur Screen size macht.

navbar sollte nicht so viel kleiner sein als der add button

2024-05-28 09:14 UTC, GolemT commented on lib/components/nav_bar.dart
> +        left: 16,
Warum brauchen wir links und rechts nen Margin? Das sieht komisch aus im letztendlichen Screen. Siehe comment in der pr #1

2024-05-28 11:40 UTC, GolemT approved these changes
LGTM!

2024-05-28 11:43 UTC, Platinchen requested changes

2024-05-28 11:43 UTC, Platinchen commented on lib/components/nav_bar.dart
> +                Icons.home,
Ich würde nochmal nach anderen Icons schauen und die vielleicht ein ticken größer machen.
Die Icons kann ich auch gerne mal nach schauen

2024-06-02 13:37 UTC, Platinchen approved these changes

2024-06-02 13:39 UTC, merged