fix: added validator for input fields
GolemT/Flutter_FinanceTracker pull request #16
Opened 2024-08-05 14:05 UTC by Phange38

2024-08-05 14:10 UTC, GolemT commented on lib/components/tag_item.dart
Description darf leer sein, ich würde den nutzer nicht zwingen eine Description anzulegen

2024-08-05 14:18 UTC, GolemT commented on lib/screens/add_transaction_screen.dart
Bug ensteht durch die Error Meldung:
Amount Feld wird dadurch einegrenzt
![grafik](https://github.com/user-attachments/assets/a580a615-b5f5-4ac2-9dad-a66baad17dc3)

2024-08-05 14:21 UTC, GolemT requested changes
Gibt es keinen Weg die Error messages direkt einzublenden? Also bei den Input feldern jeweils onChange function zu nutzen? Finde es weird das erst bei dem Finalen abschließen anzuzeigen

2024-08-06 13:38 UTC, GolemT requested changes
Fehler gefunden. Ich kann nicht mehr als 10 vorkomma stellen eingeben. damit fehlen am ende 2 Zahlen
![grafik](https://github.com/user-attachments/assets/5a2f1968-f907-43b5-901c-1aaa7228d091)
Dasselbe passiert beim add Transaction screen.

Ansonsten muss der Zahlen check auch nochmal beim Kontostand hinzugefügt werden

2024-08-07 13:59 UTC, Phange38 commented
> Fehler gefunden. Ich kann nicht mehr als 10 vorkomma stellen eingeben. damit fehlen am ende 2 Zahlen ![grafik](https://private-user-images.githubusercontent.com/79120567/355470026-5a2f1968-f907-43b5-901c-1aaa7228d091.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMzkyMzMsIm5iZiI6MTcyMzAzODkzMywicGF0aCI6Ii83OTEyMDU2Ny8zNTU0NzAwMjYtNWEyZjE5NjgtZjkwNy00M2I1LTkwMWMtMWFhYTcyMjhkMDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDEzNTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjOGE1M2VkN2VlYzczZDI0MzA5YTBhMmNmMmIzMDQ2M2I1MTY3OTkwZDdjZDFjZTg2MTkzNGY2NDA0MjhmMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8oZy04CFfpD55VbTtvx6jDdgYCqAK-YaXqHme_cjZgQ) Dasselbe passiert beim add Transaction screen.
> 
> Ansonsten muss der Zahlen check auch nochmal beim Kontostand hinzugefügt werden

lieber 12 vor dem Komma oder das Maximum reduzieren?

2024-08-08 06:31 UTC, GolemT approved these changes
LGTM!

2024-08-08 13:40 UTC, merged